apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-app
  labels: 
    app: llmops
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: llmops
  template:
    metadata:
      labels:
        app: llmops
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: llmops-container
          image: llmops-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8501
          envFrom:
            - secretRef:
                name: llmops-secrets
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: chroma-db
              mountPath: /app/chroma_db
      volumes:
        - name: chroma-db
          persistentVolumeClaim:
            claimName: chroma-db-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-db-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: llmops-service
spec:
  type: LoadBalancer
  selector:
    app: llmops
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
